default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nightingale_development

test:
  <<: *default
  database: nightingale_test

production:
  <<: *default
  database: nightingale_production
  username: nightingale
  password: <%= ENV['HEALTH_BOARD_DATABASE_PASSWORD'] %>
